### ISSUE TITLE
Chart data parse not properly.

### ISSUE THREAD

**Issue by iicdii** [hyunchel/melon-chart-api#3]
First of all, thank you for releasing this module! I'm using very well since official melon api stopped a new subscription.
```javascript
Melon(moment().format('DD/MM/YYYY'), { cutLine: 50 }).daily()
      .then(chartData => {
        if (chartData) {
          (chartData.data || []).forEach(data => {
            console.log(data);
          }
        }
      });
```
I run this code and it gives me a result below the picture.

![image](https://cloud.githubusercontent.com/assets/4951716/26814855/8cb4fe64-4ac3-11e7-9d4e-f071ae5768ce.png)

The problem is data is not parsed properly from 28th song as you see the picture.

![image](https://cloud.githubusercontent.com/assets/4951716/26814866/9e47d00c-4ac3-11e7-8442-a81c2d387f7b.png) 

I guess the 'span' tag "19금" of 28th song is parsed as song title in this picture and it causes the problem. I suggest that title is only parsed when it's in 'strong' tag or we can ignore the string "19금" while parsing.

**Comment by hyunchel** [comment]
I apologize for the delayed response.
For some odd reason, I don't remember getting this on my notification list - even though there aren't so many.

Based on your detailed ticket and suggestion, I have fixed the issue by parsing a hyperlink tag.
It seems like the title is always provided as a link.

Thank you for the feedback!
