### ISSUE TITLE
Realtime chart

### ISSUE THREAD

**Issue by Kiina** [hyunchel/melon-chart-api#6]
Would it be possible to implement the realtime chart? Without updating just being able to pull it would be okay too.

**Comment by hyunchel** [comment]
I would assume it is possible.
I will look into it and update you on this ticket.
Thank you for the suggestion!

**Comment by hyunchel** [comment]
The package now supports "realtime" chart from Melon.
The only caveat is that the method had to use an original URL from Melon - which is a bit slow to load - resulting in slower parsing time for the method.

**Comment by Kiina** [comment]
Perfect, thank you!
